version: 2.1
executors:
  docker-publisher:
    environment:
          IMAGE_NAME: gpa-tracker-api:latest
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker-compose build
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  publish-latest:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PWD
            docker tag gpa-tracker-api:latest $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME:latest
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME:latest
workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - test
      - build
      - publish-latest:
          requires:
            - build