version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - setup_remote_docker
      - run:
          name: build and publish docker image
          command: |
            docker-compose build
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PWD
            docker tag gpa-tracker-api:latest $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME:latest
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME:latest